import {
  IconBolt,
  IconBook,
  IconBrandAlipay,
  IconBrandApple,
  IconBrandGoogle,
  IconBrandGooglePlay,
  IconBrandMastercard,
  IconBrandPaypal,
  IconBrandVisa,
  IconBrandWechat,
  IconBriefcase,
  IconBuildingBank,
  IconBuildingStore,
  IconCalendar,
  IconCar,
  IconChartBar,
  IconCloud,
  IconCreditCard,
  IconDeviceDesktop,
  IconDeviceGamepad2,
  IconDots,
  IconFileInvoice,
  IconHeart,
  IconHome,
  IconMessage,
  IconMovie,
  IconMusic,
  IconNews,
  IconPlane,
  IconRepeat,
  IconShieldLock,
  IconShoppingBag,
  IconSparkles,
  IconToolsKitchen2,
  IconWallet,
  type TablerIcon,
} from "@tabler/icons-react";
import { type CommonIconKey } from "../../domain/symbol";

/**
 * The database stores application-owned tokens, never Tabler export names. Keeping
 * this registry static also prevents database content from selecting an arbitrary
 * dynamic import.
 */
export const COMMON_ICON_REGISTRY = {
  bank: IconBuildingBank,
  bolt: IconBolt,
  book: IconBook,
  brand_alipay: IconBrandAlipay,
  brand_apple: IconBrandApple,
  brand_google: IconBrandGoogle,
  brand_google_play: IconBrandGooglePlay,
  brand_mastercard: IconBrandMastercard,
  brand_paypal: IconBrandPaypal,
  // Tabler does not bundle a UnionPay glyph. Keep the stable application token and
  // deliberately render the safe generic card fallback.
  brand_unionpay: IconCreditCard,
  brand_visa: IconBrandVisa,
  brand_wechat: IconBrandWechat,
  briefcase: IconBriefcase,
  calendar: IconCalendar,
  chart: IconChartBar,
  cloud: IconCloud,
  credit_card: IconCreditCard,
  device: IconDeviceDesktop,
  dots: IconDots,
  food: IconToolsKitchen2,
  games: IconDeviceGamepad2,
  heart: IconHeart,
  home: IconHome,
  invoice: IconFileInvoice,
  message: IconMessage,
  movie: IconMovie,
  music: IconMusic,
  news: IconNews,
  security: IconShieldLock,
  shopping_bag: IconShoppingBag,
  sparkles: IconSparkles,
  store: IconBuildingStore,
  subscriptions: IconRepeat,
  transport: IconCar,
  travel: IconPlane,
  wallet: IconWallet,
} as const satisfies Readonly<Record<CommonIconKey, TablerIcon>>;
